### **Joins & Set Operations**

Q) Explain the different types of joins (inner, left, right, full, cross) and give examples of when to use each.
Q) What is a self join, and when would you use one?
Q) What is the difference between a semi join and an anti join? How can you implement them in SQL?
Q) How do UNION and UNION ALL differ? When would you use each?
Q) What are window functions in SQL, and how do they differ from aggregate functions? 
Q) Can you give an example of a query using ROW_NUMBER() or RANK()?

Q) Explain the different types of SQL joins: inner join, left join, right join, full outer join, cross join.
Q) When would you use a self-join?
Q) Can you explain what a semi-join and an anti-join are? How do they differ from regular joins?

Give answer of these in details with example

## **Q1) Explain the different types of joins (INNER, LEFT, RIGHT, FULL, CROSS) and give examples of when to use each.**  

SQL **JOINs** are used to combine rows from two or more tables based on a related column.  

### **1. INNER JOIN**  
- Returns only the **matching** rows from both tables.  
- **Use case:** When you need only records with matching values in both tables.  

```sql
SELECT 
  employees.id, 
  employees.name, 
  departments.department_name
FROM employees
INNER JOIN departments ON employees.department_id = departments.id;
```

üîπ **Example Scenario:** Retrieve employees who are assigned to a department.

### **2. LEFT JOIN (LEFT OUTER JOIN)**  
- Returns **all rows** from the left table and matching rows from the right table.  
- If there is **no match**, NULL is returned for the right table columns.  
- **Use case:** When you need **all records from the left table**, even if they have no match in the right table.  

```sql
SELECT 
   employees.id, 
   employees.name, 
   departments.department_name
   
FROM employees
LEFT JOIN departments ON employees.department_id = departments.id;
```

üîπ **Example Scenario:** Retrieve all employees, even if they are not assigned to a department.

### **3. RIGHT JOIN (RIGHT OUTER JOIN)**  
- Returns **all rows** from the right table and matching rows from the left table.  
- If there is **no match**, NULL is returned for the left table columns.  
- **Use case:** When you need **all records from the right table**, even if they have no match in the left table.  

```sql
SELECT 
   employees.id, 
   employees.name, 
   departments.department_name
   
FROM employees
RIGHT JOIN departments ON employees.department_id = departments.id;
```

üîπ **Example Scenario:** Retrieve all departments, even if they don‚Äôt have employees.

### **4. FULL JOIN (FULL OUTER JOIN)**  
- Returns **all rows** from both tables.  
- If there is no match, NULL is returned for missing values from either table.  
- **Use case:** When you need **all records from both tables**, whether they have a match or not.  

```sql
SELECT 
   employees.id, 
   employees.name, 
   departments.department_name
FROM employees
FULL JOIN departments ON employees.department_id = departments.id;
```

üîπ **Example Scenario:** Retrieve all employees and all departments, including employees with no department and departments with no employees.


### **5. CROSS JOIN**  
- Returns the **Cartesian product** of both tables (every row from table A is combined with every row from table B).  
- **Use case:** When you need all possible combinations of two sets of data.  

```sql
SELECT 
  employees.name, 
  departments.department_name
FROM employees
CROSS JOIN departments;
```

üîπ **Example Scenario:** Generate all possible employee-department combinations (useful for planning scenarios).

## **Q2) What is a self-join, and when would you use one?**  

A **self-join** is when a table is joined with itself using an alias.  

### **Use Case:**  
- Finding relationships within the same table.  
- Example: Finding employees who report to a manager.  

```sql
SELECT 
   e1.name AS Employee, 
   e2.name AS Manager
FROM employees e1
JOIN employees e2 ON e1.manager_id = e2.id;
```

üîπ **Example Scenario:** List employees along with their managers from the same employee table.


## **Q3) What is the difference between a semi-join and an anti-join? How can you implement them in SQL?**  

### **1. SEMI JOIN**  
- Returns rows from Table A **where a match exists in Table B**, but does not return columns from Table B.  
- Similar to an **INNER JOIN** but only returns Table A‚Äôs columns.  

```sql
SELECT DISTINCT employees.*
FROM employees
WHERE EXISTS (
    SELECT 1 FROM departments WHERE employees.department_id = departments.id
);
```

üîπ **Example Scenario:** Get a list of employees who belong to a department (without duplicating department data).

### **2. ANTI JOIN**  
- Returns rows from Table A **where no match exists in Table B**.  
- Similar to a **LEFT JOIN with NULL filtering**.  

```sql
SELECT employees.*
FROM employees
LEFT JOIN departments ON employees.department_id = departments.id
WHERE departments.id IS NULL;
```

üîπ **Example Scenario:** Get a list of employees who **do not belong to any department**.


## **Q4) How do UNION and UNION ALL differ? When would you use each?**  

| Feature       | UNION | UNION ALL |
|--------------|--------|----------|
| Removes Duplicates? | ‚úÖ Yes | ‚ùå No |
| Performance | Slower (sorting required) | Faster |
| When to Use | Need unique results | Need all results, including duplicates |

### **Example Usage:**
```sql
-- UNION (removes duplicates)
SELECT name FROM employees
UNION
SELECT name FROM clients;

-- UNION ALL (keeps duplicates)
SELECT name FROM employees
UNION ALL
SELECT name FROM clients;
```

üîπ **Example Scenario:**  
- Use **UNION** when combining distinct customer and supplier lists.  
- Use **UNION ALL** when merging logs from multiple sources without removing duplicates.

## **Q5) What are window functions in SQL, and how do they differ from aggregate functions?**  

### **Window Functions**  
- Perform calculations across a subset of rows **without collapsing them into a single result**.  
- Uses **OVER()** clause to define a window of rows.  

### **Difference from Aggregate Functions**  
| Feature | Aggregate Functions | Window Functions |
|---------|---------------------|------------------|
| Output | One row per group | Multiple rows |
| Uses GROUP BY? | ‚úÖ Yes | ‚ùå No |
| Example | `SUM(), COUNT()` | `ROW_NUMBER(), RANK()` |

### **Example:**
```sql
SELECT name, department_id, salary,
       AVG(salary) OVER(PARTITION BY department_id) AS avg_salary
FROM employees;
```
üîπ **Example Scenario:** Get the **average salary per department** while still displaying each employee's salary.


## **Q6) Can you give an example of a query using ROW_NUMBER() or RANK()?**  

### **1. ROW_NUMBER()**
- Assigns a unique rank to each row **without duplicates**.  

```sql
SELECT name, department_id, salary,
       ROW_NUMBER() OVER(PARTITION BY department_id ORDER BY salary DESC) AS row_num
FROM employees;
```

üîπ **Example Scenario:** Find the highest-paid employee in each department.

### **2. RANK()**
- Assigns the same rank to **duplicate values**, but skips ranks after duplicates.  

```sql
SELECT name, department_id, salary,
       RANK() OVER(PARTITION BY department_id ORDER BY salary DESC) AS rank_num
FROM employees;
```

üîπ **Example Scenario:** Find the top 3 highest-paid employees per department (handling ties properly).

## **Q7) When would you use a self-join?**  
- When querying hierarchical relationships in a single table.  
- Examples:
  - **Finding employees and their managers** (`employees` table referencing itself).  
  - **Finding customers who referred other customers** (`customers` table referencing itself).

## **Q8) Can you explain what a semi-join and an anti-join are? How do they differ from regular joins?**  
- **Semi-Join:** Returns rows from **Table A** that have a match in **Table B**.  
- **Anti-Join:** Returns rows from **Table A** that **do not** have a match in **Table B**.  
- **Regular Joins:** Return combined columns from both tables.  

### **Example (Semi-Join)**
```sql
SELECT employees.*
FROM employees
WHERE EXISTS (
    SELECT 1 FROM departments WHERE employees.department_id = departments.id
);
```

### **Example (Anti-Join)**
```sql
SELECT employees.*
FROM employees
LEFT JOIN departments ON employees.department_id = departments.id
WHERE departments.id IS NULL;
```

---

These detailed explanations and examples should give you a strong grasp of SQL joins and advanced query techniques. Let me know if you need further clarification! üöÄ

-- Joins are fundamental operations in SQL used to combine rows from two or more tables based on a related column. Among the 
-- various types of joins, **Anti Joins** and **Semi Joins** are less common but highly useful for specific scenarios.

-- ### **1. Semi Join**
--A Semi Join returns rows from one table where a match exists in another table, but it does not return columns from the second table. 
-- Essentially, it checks for the existence of matching rows and returns only those rows from the first table.

--**Use Case:** Finding rows in one table that have matching rows in another table, but you only need the rows from the first table.

#### **Example**

Assume we have two tables:

- **Customers**:
  - `customer_id`
  - `customer_name`

- **Orders**:
  - `order_id`
  - `customer_id`
  - `order_date`

**Task:** Find all customers who have placed at least one order.

**SQL Query:**

```sql
SELECT customer_id, customer_name
FROM Customers c
WHERE EXISTS (
    SELECT 1
    FROM Orders o
    WHERE o.customer_id = c.customer_id
);
```

**Explanation:**
- The `EXISTS` subquery checks if there are any rows in the `Orders` table with the same `customer_id` as in the `Customers` table.
- If such rows exist, the `customer_id` and `customer_name` from the `Customers` table are returned.


--### **2. Anti Join**
-- An Anti Join returns rows from one table where no match exists in another table. It is the opposite of a Semi Join. 
--Essentially, it filters out rows from the first table that have matching rows in the second table.

**Use Case:** Finding rows in one table that do not have corresponding rows in another table.

#### **Example**

Continuing with the same tables:

- **Customers**:
  - `customer_id`
  - `customer_name`

- **Orders**:
  - `order_id`
  - `customer_id`
  - `order_date`

--**Task:** Find all customers who have not placed any orders.

**SQL Query:**

```sql
SELECT customer_id, customer_name
FROM Customers c
WHERE NOT EXISTS (
    SELECT 1
    FROM Orders o
    WHERE o.customer_id = c.customer_id
);
```

**Explanation:**
- The `NOT EXISTS` subquery checks if there are no rows in the `Orders` table with the same `customer_id` as in the `Customers` table.
- If no such rows exist, the `customer_id` and `customer_name` from the `Customers` table are returned.

### **Alternative Methods for Semi and Anti Joins**

In addition to using `EXISTS` and `NOT EXISTS`, you can achieve similar results 
1. using `LEFT JOIN` with `IS NULL` for Anti Joins 
2. and `INNER JOIN` for Semi Joins.

#### **Semi Join Alternative with `INNER JOIN`**

```sql
SELECT DISTINCT c.customer_id, c.customer_name
FROM Customers c
INNER JOIN Orders o ON c.customer_id = o.customer_id;
```

**Explanation:**
- This query performs an `INNER JOIN` and uses `DISTINCT` to ensure each customer appears only once.

-- #### **Anti Join Alternative with `LEFT JOIN` and `IS NULL`**

```sql
SELECT c.customer_id, c.customer_name
FROM Customers c
LEFT JOIN Orders o ON c.customer_id = o.customer_id
WHERE o.customer_id IS NULL;
```

**Explanation:**
- The `LEFT JOIN` returns all rows from `Customers` and matches rows from `Orders`. Rows in `Customers` with no match in `Orders` 
will have `NULL` values in the `Orders` columns.
- The `WHERE o.customer_id IS NULL` condition filters out customers who have not placed any orders.